version: '3.3'

services:

  redis:
    container_name: nosql_redis
    image: redis:5
    restart: always
    command: redis-server --port 6380 --requirepass Jasinski
    ports:
      - 6380:6380
    